### ISSUE TITLE
mapStallingProducer with certain arguments blocks value emission

### ISSUE THREAD

**Issue by beckyconning** [slamdata/purescript-stalling-coroutines#5]
The producer returned by the following snippet never emits any values

```
getIdTokenStorageEvents
  ∷ ∀ eff
  . Eff (dom :: DOM, avar :: AVAR | eff) (StallingProducer (StorageEvent (Either String IdToken)) (Aff (dom :: DOM, avar :: AVAR | eff)) Unit)
getIdTokenStorageEvents =
  StallingCoroutine.mapStallingProducer stringValuesToIdTokens
    ∘ StallingCoroutine.filter isIdTokenKeyEvent
    ∘ StallingCoroutine.producerToStallingProducer
    <$> LocalStorage.getStorageEventProducer false
  where
  isIdTokenKeyEvent o = o.key == AuthKeys.idTokenLocalStorageKey
  stringValuesToIdTokens e = e { newValue = map IdToken e.newValue, oldValue = map IdToken e.oldValue }
```

But the one returned by this snippet does

```
getIdTokenStorageEvents
  ∷ ∀ eff
  . Eff (dom :: DOM, avar :: AVAR | eff) (StallingProducer (StorageEvent (Either String String)) (Aff (dom :: DOM, avar :: AVAR | eff)) Unit)
getIdTokenStorageEvents =
   StallingCoroutine.filter isIdTokenKeyEvent
    ∘ StallingCoroutine.producerToStallingProducer
    <$> LocalStorage.getStorageEventProducer false
  where
  isIdTokenKeyEvent o = o.key == AuthKeys.idTokenLocalStorageKey
```

**Comment by beckyconning** [comment]
My theory is that this might be because not all `newValue`s and `oldValue`s before the filter are `Functor`s. If I'm right then something is not type safe.

**Comment by jdegoes** [comment]
You could `spy` on the values being mapped over as a next step.

**Comment by beckyconning** [comment]
ah i think it might be because the `oldValue` may be `null` rather than an error with stallingCoroutine.

**Comment by garyb** [comment]
How does that happen, is it from the storage stuff? Neither `coroutines` or `stalling-coroutines` involve any FFI code.

**Comment by beckyconning** [comment]
By my last comment I mean now that I'm looking at this again I don't think the problem I'm running into is a problem in this package. I'm just confirming this now and if its the case I'll close this issue.

**Comment by beckyconning** [comment]
Yep this wasn't an issue with stalling coroutines. For anyone running into a similar issue `Foreign` is your friend.
